name: Build MacroFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          platform: android64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacroFlow-android64
          path: build/*.geode
